### PR TITLE
ci: Add minimal CI using GitHub Actions.

### PR DESCRIPTION
**Pull request by waywardmonkeys**
This adds some minimal CI that:

* Checks code formatting.
* Runs tests on the main crate.
* Runs clippy on the main crate.
* Runs clippy to make sure the benchmark compiles.

It does not do anything with the examples crate yet as that doesn't currently compile.

### CODE REVIEW

**Review by bonsairobo — APPROVED** [review]

**Comment by bonsairobo** [comment]
Thanks!

**Comment by eadf** [comment]
What does the benchmarks do in the github actions (other than test that they do not crash)?

Also, just a heads up: Adding github actions though git commands does nothing, the last time i tried that i had to use Actions->New workflow for the action to actually start.

**Comment by waywardmonkeys** [comment]
@eadf Just makes sure they compile and have no clippy warnings.

**Comment by eadf** [comment]
ah, right. I didn't check that carefully. I thought it actually ran the benchmarks. Isc

**Pull request merged**
